server:
  port: 10010
spring:
  application:
    name: friday-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /friday # 路由路径前缀
  routes:
    user-service: /user/** # 用户微服务的映射路径
    bills-service: /bills/** # 账单微服务映射路径
    finance-service: /finance/** #基金与股票微服务
    equity-service: /equity/** #固定资产与债务
    report-service: /report/** #报表微服务